### ISSUE TITLE
[refactoring] 전반적인 구조 리펙토링 및 테스트 파일 생성 #1

### ISSUE THREAD

**Issue by wnet500** [Jovinus/Autonomic_Aging#1]
### A.코드 내부 수정
- 자체 library import rule 적용
  - 외부 라이브러리 (import로 시작) -> 외부 라이브러리 (from으로 시작) -> 내부 모듈 (import로 시작) -> 내부 모듈 (from 으로 시작)
  한 줄씩 띄어서 위 4가지 분류를 구분 
- 각 분류 내부 라이브러리는 알파벳 순으로 작성

- pep8 convention 적용 (코딩하는 사람들이 전반적으로 약속한 코딩 작성 룰 - 띄어쓰기 등)
  - `pip install autopep8` 으로 설치 후, 전체 스크립트 선택 후 `command + K + F`로 사용

- 변수 이름 변경
dictionary, list, array, dataframe 등은 변수이름만 봐도 타입을 알 수 있도록 `{변수이름}_dict`, `{변수이름}_list` 등으로 작명

- 함수명
한 스크립트 내부에서만 사용되는 함수는 앞에 "_" 붙여주기 (내부함수라는 표시)
예) "get_data_info" 와 "dat_to_json" 함수는 "make_dataset"에 최종 사용되기 위해 정의한 함수이므로
"_get_data_info" 와 "_dat_to_json"로 변경

- f-string 사용
  - 보통 string에 변수의 값을 넣기 위해서 "+"와 ".format"을 많이 쓰나, f-string이 가장 빠르고 장점이 많으므로 f-string 사용권장
  예시)
    ```
    my_age = 29
    print_string_1 = f"I'm {my_age} years old." # 권장
    print_string_2 = "I'm " + string(my_age) + " years old." # 비권장, 코드 깔끔성 떨어짐
    print_string_3 = "I'm {} years old".format(my_age) # f-string보다 느림
    print(print_string_1)
    ```
- 여러가지 인자를 입력한 경우
[권장]
  ```
  my_dict = {
      "name": ["a", "b", "c"],
      "age": [1, 2, 3]
  }
  ```
    [비권장]
  ```
  my_dict = {"name": ["a", "b", "c"],
            "age": [1, 2, 3]}
   ```
- 코드 공백 사이즈
  - 공백 2 사용 권장
  - vscode 오른쪽 아래서 공백 4 -> 2로 변경

### B. 테스트 파일 생성
- `tests/test_code.py` 생성
-  한 스크립트 내부에 `if __name__ == '__main__':`을 사용하지 않고 tests 폴더 내부에 각 클래스, 함수 등을 테스트 해보고 오류를 발견하도록 연습하는 것을 권장
- 터미널에 `pytest -s -v tests/test_code.py::test_make_dataset` 다음 코드 실행

**Comment by Jovinus** [comment]
Issue is solved
